#!/usr/bin/env ruby

path = ENV["ADHOCPATH"] || File.expand_path("~/.adhoc")

if !File.exists?(path)
  $stderr.puts "Could not find the directory for workers"
  $stderr.puts "Searched in #{path}"
  $stderr.puts "You can specify an alternate path with the environment variable $ADHOCPATH"
  exit 1
end

lang, *rest = ARGV

if lang =~ /--.*/
  lang = lang[2..-1]
  lang = "rb" if lang == ""
  args = rest
else
  lang = "rb"
  args = ARGV
end
langre = Regexp.new("\\b" + lang + "\\b")

candidates = `ls #{path}`.sort.select do |filename|
  filename.match(langre) && !filename.match(/~$/)
end

if candidates.empty?
  $stderr.puts "Could not find language '#{lang}'"
  $stderr.puts "Available workers can be found in #{path}"
elsif candidates.count > 1
  $stderr.puts "There are more than one worker for '#{lang}':"
  $stderr.puts candidates
  $stderr.puts "Available workers can be found in #{path}"
else
  candidates.each do |filename|
    filename = filename.strip
    system("#{path}/#{filename}", *args)
  end
end

