#!/usr/bin/env ruby

path = ENV["ADHOCPATH"] || File.expand_path("~/.adhoc")

if !File.exists?(path)
  $stderr.puts "Could not find the directory for scripts"
  $stderr.puts "Searched in #{path}"
  $stderr.puts "You can specify an alternate path with the environment variable $ADHOCPATH"
  exit 1
end

lang, *rest = ARGV

if lang =~ /--.*/ and lang != "--help"
  lang = lang[2..-1]
  lang = "default" if lang == ""
  args = rest
else
  lang = "default"
  args = ARGV
end
langre = Regexp.new("\\b" + lang + "\\b")

candidates = `ls #{path}`.sort.select do |filename|
  filename.match(langre) && !filename.match(/~$/)
end

if candidates.empty?
  $stderr.puts "Could not find language '#{lang}'"
  $stderr.puts "Available scripts can be found in #{path}"
elsif candidates.count > 1
  $stderr.puts "There are more than one worker for '#{lang}':"
  $stderr.puts candidates
  $stderr.puts "Available scripts can be found in #{path}"
else
  candidates.each do |filename|
    filename = filename.strip
    script = "#{path}/#{filename}"
    rval = system(script, *args)
    if !rval and $? != 256 # exit code 1
      $stderr.puts "Error executing script '#{script}'"
      if $?>>8 >= 126
        $stderr.puts "Does the file exist and are the permission bits set for execute?"
      end
    end
  end
end

